name: Deploy AWS EC2

on:
  push:
    branches:
      - dev   # trigger only when pushing to dev branch

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 via PM2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '

            # meaning resolved_path = /home/ubuntu/St-Augusta-Public-School
            resolved_path=$(eval echo "$HOME/St-Augusta-Public-School") 
            REPO_DIR=""

            if [ -d "$resolved_path/.git" ]; then
              REPO_DIR="$resolved_path"
            fi

            if [ -n "$REPO_DIR" ]; then 
              echo "Found repository at: $REPO_DIR"
              cd "$REPO_DIR" 
              
              echo "Fetching latest changes..."
              git fetch --all

              echo "Resetting to latest..."
              git reset --hard origin/dev

              echo "Running deployment script..."
              bash deploy.sh
            else

              git clone https://github.com/aviralsingh28/St-Augusta-Public-School.git "$resolved_path"
              cd "$resolved_path"
              
              echo "Running deployment script..."  
              bash deploy.sh
            fi

            echo "Running deployment script..."
            npm ci --legacy-peer-deps
            npx prisma generate
            npx prisma migrate deploy || echo "Migrations skipped"
            npm run build
            PORT=3000 pm2 restart St-Augusta-Public-School || PORT=3000 pm2 start npm --name "St-Augusta-Public-School" -- start
            pm2 save
          '